### ISSUE TITLE
first good issue php 

### ISSUE THREAD

**Issue by hasnahadd** [hasnahadd/FirstProject#1]
problem with the quantity when we submit the checkout

**Comment by omdodmani251** [comment]
Hello, The cloned project is not working due to a missing database file named **'testecommerce'** please include it in the repository. Thanks

**Comment by hasnahadd** [comment]
u need to clone the branch main i will add the database the database is in the brach main called bd.sql u can download it then add it to the server

Le ven. 21 juil. 2023 à 10:15, Om Dodmani ***@***.***> a
écrit :

**Comment by Decent-Coder** [comment]
I have fixed the issue, trying to push but getting 403

**Comment by hasnahadd** [comment]
thank u so much sir

Le sam. 19 août 2023 à 10:56, Yogesh sahu ***@***.***> a
écrit :

**Comment by yogesh-sahu** [comment]
welcome 😉
